// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MovieCollection.DAL.Contexts;

#nullable disable

namespace MovieCollection.DAL.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230108134036_InitialMigration02a")]
    partial class InitialMigration02a
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("MovieCollection.DAL.Models.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("tblCountries", "Country");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Afghanistan"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Albania"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Algeria"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Andorra"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Angola"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Antigua and Barbuda"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Argentina"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Armenia"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Australia"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Austria"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Azerbaijan"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Bahamas"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Bahrain"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Bangladesh"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Barbados"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Belarus"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Belgium"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Belize"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Benin"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Bhutan"
                        },
                        new
                        {
                            Id = 21,
                            Name = "Bolivia"
                        },
                        new
                        {
                            Id = 22,
                            Name = "Bosnia and Herzegovina"
                        },
                        new
                        {
                            Id = 23,
                            Name = "Botswana"
                        },
                        new
                        {
                            Id = 24,
                            Name = "Brazil"
                        },
                        new
                        {
                            Id = 25,
                            Name = "Brunei"
                        },
                        new
                        {
                            Id = 26,
                            Name = "Bulgaria"
                        },
                        new
                        {
                            Id = 27,
                            Name = "Burkina Faso"
                        },
                        new
                        {
                            Id = 28,
                            Name = "Burundi"
                        },
                        new
                        {
                            Id = 29,
                            Name = "Côte d'Ivoire"
                        },
                        new
                        {
                            Id = 30,
                            Name = "Cabo Verde"
                        },
                        new
                        {
                            Id = 31,
                            Name = "Cambodia"
                        },
                        new
                        {
                            Id = 32,
                            Name = "Cameroon"
                        },
                        new
                        {
                            Id = 33,
                            Name = "Canada"
                        },
                        new
                        {
                            Id = 34,
                            Name = "Central African Republic"
                        },
                        new
                        {
                            Id = 35,
                            Name = "Chad"
                        },
                        new
                        {
                            Id = 36,
                            Name = "Chile"
                        },
                        new
                        {
                            Id = 37,
                            Name = "China"
                        },
                        new
                        {
                            Id = 38,
                            Name = "Colombia"
                        },
                        new
                        {
                            Id = 39,
                            Name = "Comoros"
                        },
                        new
                        {
                            Id = 40,
                            Name = "Congo (Congo-Brazzaville)"
                        },
                        new
                        {
                            Id = 41,
                            Name = "Costa Rica"
                        },
                        new
                        {
                            Id = 42,
                            Name = "Croatia"
                        },
                        new
                        {
                            Id = 43,
                            Name = "Cuba"
                        },
                        new
                        {
                            Id = 44,
                            Name = "Cyprus"
                        },
                        new
                        {
                            Id = 45,
                            Name = "Czechia (Czech Republic)"
                        },
                        new
                        {
                            Id = 46,
                            Name = "Democratic Republic of the Congo"
                        },
                        new
                        {
                            Id = 47,
                            Name = "Denmark"
                        },
                        new
                        {
                            Id = 48,
                            Name = "Djibouti"
                        },
                        new
                        {
                            Id = 49,
                            Name = "Dominica"
                        },
                        new
                        {
                            Id = 50,
                            Name = "Dominican Republic"
                        },
                        new
                        {
                            Id = 51,
                            Name = "Ecuador"
                        },
                        new
                        {
                            Id = 52,
                            Name = "Egypt"
                        },
                        new
                        {
                            Id = 53,
                            Name = "El Salvador"
                        },
                        new
                        {
                            Id = 54,
                            Name = "Equatorial Guinea"
                        },
                        new
                        {
                            Id = 55,
                            Name = "Eritrea"
                        },
                        new
                        {
                            Id = 56,
                            Name = "Estonia"
                        },
                        new
                        {
                            Id = 57,
                            Name = "Eswatini (fmr. \"Swaziland\")"
                        },
                        new
                        {
                            Id = 58,
                            Name = "Ethiopia"
                        },
                        new
                        {
                            Id = 59,
                            Name = "Fiji"
                        },
                        new
                        {
                            Id = 60,
                            Name = "Finland	"
                        },
                        new
                        {
                            Id = 61,
                            Name = "France"
                        },
                        new
                        {
                            Id = 62,
                            Name = "Gabon"
                        },
                        new
                        {
                            Id = 63,
                            Name = "Gambia"
                        },
                        new
                        {
                            Id = 64,
                            Name = "Georgia"
                        },
                        new
                        {
                            Id = 65,
                            Name = "Germany"
                        },
                        new
                        {
                            Id = 66,
                            Name = "Ghana"
                        },
                        new
                        {
                            Id = 67,
                            Name = "Greece"
                        },
                        new
                        {
                            Id = 68,
                            Name = "Grenada"
                        },
                        new
                        {
                            Id = 69,
                            Name = "Guatemala"
                        },
                        new
                        {
                            Id = 70,
                            Name = "Guinea"
                        },
                        new
                        {
                            Id = 71,
                            Name = "Guinea-Bissau"
                        },
                        new
                        {
                            Id = 72,
                            Name = "Guyana"
                        },
                        new
                        {
                            Id = 73,
                            Name = "Haiti"
                        },
                        new
                        {
                            Id = 74,
                            Name = "Holy See"
                        },
                        new
                        {
                            Id = 75,
                            Name = "Honduras"
                        },
                        new
                        {
                            Id = 76,
                            Name = "Hungary"
                        },
                        new
                        {
                            Id = 77,
                            Name = "Iceland"
                        },
                        new
                        {
                            Id = 78,
                            Name = "India"
                        },
                        new
                        {
                            Id = 79,
                            Name = "Indonesia"
                        },
                        new
                        {
                            Id = 80,
                            Name = "Iran"
                        },
                        new
                        {
                            Id = 81,
                            Name = "Iraq"
                        },
                        new
                        {
                            Id = 82,
                            Name = "Ireland"
                        },
                        new
                        {
                            Id = 83,
                            Name = "Israel"
                        },
                        new
                        {
                            Id = 84,
                            Name = "Italy"
                        },
                        new
                        {
                            Id = 85,
                            Name = "Jamaica"
                        },
                        new
                        {
                            Id = 86,
                            Name = "Japan"
                        },
                        new
                        {
                            Id = 87,
                            Name = "Jordan"
                        },
                        new
                        {
                            Id = 88,
                            Name = "Kazakhstan"
                        },
                        new
                        {
                            Id = 89,
                            Name = "Kenya"
                        },
                        new
                        {
                            Id = 90,
                            Name = "Kiribati"
                        },
                        new
                        {
                            Id = 91,
                            Name = "Kuwait"
                        },
                        new
                        {
                            Id = 92,
                            Name = "Kyrgyzstan"
                        },
                        new
                        {
                            Id = 93,
                            Name = "Laos"
                        },
                        new
                        {
                            Id = 94,
                            Name = "Latvia"
                        },
                        new
                        {
                            Id = 95,
                            Name = "Lebanon"
                        },
                        new
                        {
                            Id = 96,
                            Name = "Lesotho"
                        },
                        new
                        {
                            Id = 97,
                            Name = "Liberia"
                        },
                        new
                        {
                            Id = 98,
                            Name = "Libya"
                        },
                        new
                        {
                            Id = 99,
                            Name = "Liechtenstein"
                        },
                        new
                        {
                            Id = 100,
                            Name = "Lithuania"
                        },
                        new
                        {
                            Id = 101,
                            Name = "Luxembourg"
                        },
                        new
                        {
                            Id = 102,
                            Name = "Madagascar"
                        },
                        new
                        {
                            Id = 103,
                            Name = "Malawi"
                        },
                        new
                        {
                            Id = 104,
                            Name = "Malaysia"
                        },
                        new
                        {
                            Id = 105,
                            Name = "Maldives"
                        },
                        new
                        {
                            Id = 106,
                            Name = "Mali"
                        },
                        new
                        {
                            Id = 107,
                            Name = "Malta"
                        },
                        new
                        {
                            Id = 108,
                            Name = "Marshall Islands"
                        },
                        new
                        {
                            Id = 109,
                            Name = "Mauritania"
                        },
                        new
                        {
                            Id = 110,
                            Name = "Mauritius"
                        },
                        new
                        {
                            Id = 111,
                            Name = "Mexico"
                        },
                        new
                        {
                            Id = 112,
                            Name = "Micronesia"
                        },
                        new
                        {
                            Id = 113,
                            Name = "Moldova"
                        },
                        new
                        {
                            Id = 114,
                            Name = "Monaco"
                        },
                        new
                        {
                            Id = 115,
                            Name = "Mongolia"
                        },
                        new
                        {
                            Id = 116,
                            Name = "Montenegro"
                        },
                        new
                        {
                            Id = 117,
                            Name = "Morocco"
                        },
                        new
                        {
                            Id = 118,
                            Name = "Mozambique"
                        },
                        new
                        {
                            Id = 119,
                            Name = "Myanmar (formerly Burma)"
                        },
                        new
                        {
                            Id = 120,
                            Name = "Namibia"
                        },
                        new
                        {
                            Id = 121,
                            Name = "Nauru"
                        },
                        new
                        {
                            Id = 122,
                            Name = "Nepal"
                        },
                        new
                        {
                            Id = 123,
                            Name = "Netherlands"
                        },
                        new
                        {
                            Id = 124,
                            Name = "New Zealand"
                        },
                        new
                        {
                            Id = 125,
                            Name = "Nicaragua"
                        },
                        new
                        {
                            Id = 126,
                            Name = "Niger"
                        },
                        new
                        {
                            Id = 127,
                            Name = "Nigeria"
                        },
                        new
                        {
                            Id = 128,
                            Name = "North Korea"
                        },
                        new
                        {
                            Id = 129,
                            Name = "North Macedonia"
                        },
                        new
                        {
                            Id = 130,
                            Name = "Norway"
                        },
                        new
                        {
                            Id = 131,
                            Name = "Oman"
                        },
                        new
                        {
                            Id = 132,
                            Name = "Pakistan"
                        },
                        new
                        {
                            Id = 133,
                            Name = "Palau"
                        },
                        new
                        {
                            Id = 134,
                            Name = "Palestine State"
                        },
                        new
                        {
                            Id = 135,
                            Name = "Panama"
                        },
                        new
                        {
                            Id = 136,
                            Name = "Papua New Guinea"
                        },
                        new
                        {
                            Id = 137,
                            Name = "Paraguay"
                        },
                        new
                        {
                            Id = 138,
                            Name = "Peru"
                        },
                        new
                        {
                            Id = 139,
                            Name = "Philippines"
                        },
                        new
                        {
                            Id = 140,
                            Name = "Poland"
                        },
                        new
                        {
                            Id = 141,
                            Name = "Portugal"
                        },
                        new
                        {
                            Id = 142,
                            Name = "Qatar"
                        },
                        new
                        {
                            Id = 143,
                            Name = "Romania"
                        },
                        new
                        {
                            Id = 144,
                            Name = "Russia"
                        },
                        new
                        {
                            Id = 145,
                            Name = "Rwanda"
                        },
                        new
                        {
                            Id = 146,
                            Name = "Saint Kitts and Nevis"
                        },
                        new
                        {
                            Id = 147,
                            Name = "Saint Lucia"
                        },
                        new
                        {
                            Id = 148,
                            Name = "Saint Vincent and the Grenadines"
                        },
                        new
                        {
                            Id = 149,
                            Name = "Samoa"
                        },
                        new
                        {
                            Id = 150,
                            Name = "San Marino"
                        },
                        new
                        {
                            Id = 151,
                            Name = "Sao Tome and Principe"
                        },
                        new
                        {
                            Id = 152,
                            Name = "Saudi Arabia"
                        },
                        new
                        {
                            Id = 153,
                            Name = "Senegal"
                        },
                        new
                        {
                            Id = 154,
                            Name = "Serbia"
                        },
                        new
                        {
                            Id = 155,
                            Name = "Seychelles"
                        },
                        new
                        {
                            Id = 156,
                            Name = "Sierra Leone"
                        },
                        new
                        {
                            Id = 157,
                            Name = "Singapore"
                        },
                        new
                        {
                            Id = 158,
                            Name = "Slovakia"
                        },
                        new
                        {
                            Id = 159,
                            Name = "Slovenia"
                        },
                        new
                        {
                            Id = 160,
                            Name = "Solomon Islands"
                        },
                        new
                        {
                            Id = 161,
                            Name = "Somalia"
                        },
                        new
                        {
                            Id = 162,
                            Name = "South Africa"
                        },
                        new
                        {
                            Id = 163,
                            Name = "South Korea"
                        },
                        new
                        {
                            Id = 164,
                            Name = "South Sudan"
                        },
                        new
                        {
                            Id = 165,
                            Name = "Spain"
                        },
                        new
                        {
                            Id = 166,
                            Name = "Sri Lanka"
                        },
                        new
                        {
                            Id = 167,
                            Name = "Sudan"
                        },
                        new
                        {
                            Id = 168,
                            Name = "Suriname"
                        },
                        new
                        {
                            Id = 169,
                            Name = "Sweden"
                        },
                        new
                        {
                            Id = 170,
                            Name = "Switzerland"
                        },
                        new
                        {
                            Id = 171,
                            Name = "Syria"
                        },
                        new
                        {
                            Id = 172,
                            Name = "Tajikistan"
                        },
                        new
                        {
                            Id = 173,
                            Name = "Tanzania"
                        },
                        new
                        {
                            Id = 174,
                            Name = "Thailand"
                        },
                        new
                        {
                            Id = 175,
                            Name = "Timor-Leste"
                        },
                        new
                        {
                            Id = 176,
                            Name = "Togo"
                        },
                        new
                        {
                            Id = 177,
                            Name = "Tonga"
                        },
                        new
                        {
                            Id = 178,
                            Name = "Trinidad and Tobago"
                        },
                        new
                        {
                            Id = 179,
                            Name = "Tunisia"
                        },
                        new
                        {
                            Id = 180,
                            Name = "Turkey"
                        },
                        new
                        {
                            Id = 181,
                            Name = "Turkmenistan"
                        },
                        new
                        {
                            Id = 182,
                            Name = "Tuvalu"
                        },
                        new
                        {
                            Id = 183,
                            Name = "Uganda"
                        },
                        new
                        {
                            Id = 184,
                            Name = "Ukraine"
                        },
                        new
                        {
                            Id = 185,
                            Name = "United Arab Emirates"
                        },
                        new
                        {
                            Id = 186,
                            Name = "United Kingdom"
                        },
                        new
                        {
                            Id = 187,
                            Name = "United States of America"
                        },
                        new
                        {
                            Id = 188,
                            Name = "Uruguay"
                        },
                        new
                        {
                            Id = 189,
                            Name = "Uzbekistan"
                        },
                        new
                        {
                            Id = 190,
                            Name = "Vanuatu"
                        },
                        new
                        {
                            Id = 191,
                            Name = "Venezuela"
                        },
                        new
                        {
                            Id = 192,
                            Name = "Vietnam"
                        },
                        new
                        {
                            Id = 193,
                            Name = "Yemen"
                        },
                        new
                        {
                            Id = 194,
                            Name = "Zambia"
                        },
                        new
                        {
                            Id = 195,
                            Name = "Zimbabwe"
                        });
                });

            modelBuilder.Entity("MovieCollection.DAL.Models.Director", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("varchar(25)");

                    b.Property<string>("IsActive")
                        .IsRequired()
                        .HasColumnType("varchar(25)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("varchar(25)");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasColumnType("varchar(25)");

                    b.Property<string>("PicturePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("tblDirectors", "Director");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateOfBirth = new DateTime(1965, 2, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Michael",
                            IsActive = "Yes",
                            LastName = "Bay",
                            Nationality = "American",
                            PicturePath = "/images/MichaelBay.png"
                        },
                        new
                        {
                            Id = 2,
                            DateOfBirth = new DateTime(1970, 7, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Christopher",
                            IsActive = "Yes",
                            LastName = "Nolan",
                            Nationality = "English",
                            PicturePath = "/images/ChristopherNolan.png"
                        },
                        new
                        {
                            Id = 3,
                            DateOfBirth = new DateTime(1937, 11, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Ridley",
                            IsActive = "Yes",
                            LastName = "Scott",
                            Nationality = "English",
                            PicturePath = "/images/RidleyScott.png"
                        },
                        new
                        {
                            Id = 4,
                            DateOfBirth = new DateTime(1935, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Woody",
                            IsActive = "No",
                            LastName = "Allen",
                            Nationality = "American",
                            PicturePath = "/images/WoodyAllen.png"
                        },
                        new
                        {
                            Id = 5,
                            DateOfBirth = new DateTime(1961, 10, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Peter",
                            IsActive = "Yes",
                            LastName = "Jackson",
                            Nationality = "New Zealander",
                            PicturePath = "/images/PeterJackson.png"
                        });
                });

            modelBuilder.Entity("MovieCollection.DAL.Models.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(25)");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("tblGenres", "Genre");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Action"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Adventure"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Animation"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Comedy"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Devotional"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Drama"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Hindu mythology"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Historical"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Horror"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Science fiction"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Western"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Other"
                        });
                });

            modelBuilder.Entity("MovieCollection.DAL.Models.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<int>("DirectorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("date");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.HasIndex("DirectorId");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("tblMovies", "Movie");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CountryId = 187,
                            DirectorId = 1,
                            ReleaseDate = new DateTime(2003, 10, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Bad Boys 2"
                        },
                        new
                        {
                            Id = 2,
                            CountryId = 186,
                            DirectorId = 2,
                            ReleaseDate = new DateTime(2020, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Tenet"
                        },
                        new
                        {
                            Id = 3,
                            CountryId = 186,
                            DirectorId = 3,
                            ReleaseDate = new DateTime(1979, 9, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Aliens"
                        },
                        new
                        {
                            Id = 4,
                            CountryId = 187,
                            DirectorId = 4,
                            ReleaseDate = new DateTime(2011, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Midnight in Paris"
                        },
                        new
                        {
                            Id = 5,
                            CountryId = 124,
                            DirectorId = 5,
                            ReleaseDate = new DateTime(2005, 12, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "King Kong"
                        });
                });

            modelBuilder.Entity("MovieCollection.DAL.Models.MovieGenre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("GenreId")
                        .HasColumnType("int");

                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GenreId");

                    b.HasIndex("MovieId");

                    b.ToTable("MovieGenre");
                });

            modelBuilder.Entity("MovieCollection.DAL.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("varchar(25)");

                    b.Property<string>("IsActive")
                        .IsRequired()
                        .HasColumnType("varchar(25)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("varchar(25)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("tblUsers", "User");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "Nabil_EM@outlook.com",
                            FirstName = "Nabil",
                            IsActive = "Yes",
                            LastName = "El Moussaoui"
                        },
                        new
                        {
                            Id = 2,
                            Email = "Abdelmajid.Amiri@outlook.com",
                            FirstName = "Abdelmajid",
                            IsActive = "Yes",
                            LastName = "Amiri"
                        },
                        new
                        {
                            Id = 3,
                            Email = "Azdine.ElJattari@outlook.com",
                            FirstName = "Azdine",
                            IsActive = "No",
                            LastName = "El Jattari"
                        },
                        new
                        {
                            Id = 4,
                            Email = "Mohamed.Azdad@outlook.com",
                            FirstName = "Mohamed",
                            IsActive = "Yes",
                            LastName = "Azdad"
                        },
                        new
                        {
                            Id = 5,
                            Email = "Mirwahaj.Waez@outlook.com",
                            FirstName = "Mirwahaj",
                            IsActive = "No",
                            LastName = "Waez"
                        });
                });

            modelBuilder.Entity("MovieCollection.DAL.Models.Movie", b =>
                {
                    b.HasOne("MovieCollection.DAL.Models.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MovieCollection.DAL.Models.Director", "Director")
                        .WithMany()
                        .HasForeignKey("DirectorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Country");

                    b.Navigation("Director");
                });

            modelBuilder.Entity("MovieCollection.DAL.Models.MovieGenre", b =>
                {
                    b.HasOne("MovieCollection.DAL.Models.Genre", "Genre")
                        .WithMany("MovieGenres")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MovieCollection.DAL.Models.Movie", "Movie")
                        .WithMany("MovieGenres")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genre");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("MovieCollection.DAL.Models.Genre", b =>
                {
                    b.Navigation("MovieGenres");
                });

            modelBuilder.Entity("MovieCollection.DAL.Models.Movie", b =>
                {
                    b.Navigation("MovieGenres");
                });
#pragma warning restore 612, 618
        }
    }
}
